[package]
name        = "hexo_synth"
version     = "0.1.0"
authors     = ["Weird Constructor <weirdconstructor@m8geil.de>"]
license     = "AGPL-3.0-or-later"
edition     = "2018"
description = "HexoSynth - A hexagonal modular synthesizer plugin"

[dependencies]
hexotk     = { git = "https://m8geil.de:3000/WeirdConstructor/HexoTK.git" }
baseplug   = { git = "https://github.com/wrl/baseplug.git" }
serde      = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
ringbuf    = "0.2.2"

[lib]
name="hexosynth"
crate-type = ["cdylib", "lib"]
